Calculos Matriciales

In [7]:
import numpy as np

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

#Suma
sum = A + B
print(A)
print(B)
print("\nSuma de matrices:")
print(sum)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]

Suma de matrices:
[[ 6  8]
 [10 12]]


In [8]:
#Substraction
res = B - A
print("Resta de matrices:")
print(res)

Resta de matrices:
[[4 4]
 [4 4]]


In [9]:
#Multiplication
product = np.dot(A, B)
print("Multiplicacion entre matrices:")
print(product)

Multiplicacion entre matrices:
[[19 22]
 [43 50]]


In [12]:
#Determinante
det_A = np.linalg.det(A)
#Inversa
inv_A = np.linalg.inv(A)
print(A)
print(det_A)
print(inv_A)

[[1 2]
 [3 4]]
-2.0000000000000004
[[-2.   1. ]
 [ 1.5 -0.5]]


In [13]:
#Resolver Ax = b
#Sistema de ecuaciones lineales
b = np.array([9, 11])
x = np.linalg.solve(A, b)
print(x)

[-7.  8.]
