In [1]:
import numpy as np

prices = np.array([100,200,300])
discount = np.array([0.9])
discount_prices = prices * discount
print(discount_prices)

[ 90. 180. 270.]


In [4]:
prices = np.random.randint(100, 500, size=(3,3))
discount = np.array([10, 20, 30])
discount_prices = prices + discount
print(prices)
print(discount_prices)

[[142 132 496]
 [340 435 218]
 [128 274 283]]
[[152 152 526]
 [350 455 248]
 [138 294 313]]


In [6]:
array = np.array([1,2,3,4,5])
print(np.all(array > 9))

False


In [9]:
print(np.any(array > 0))

True


In [11]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
concatenated_a = np.concatenate((array_a, array_a))
concatenated = np.concatenate((array_a, array_b))
print(concatenated_a)
print(concatenated)

[1 2 3 1 2 3]
[1 2 3 4 5 6]


In [12]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
stacked_v =np.vstack((array_a, array_b))
print(stacked_v)

[[1 2 3]
 [4 5 6]]


In [13]:
array_a = np.array([1,2,3])
array_b = np.array([4,5,6])
stacked_h =np.hstack((array_a, array_b))
print(stacked_h)

[1 2 3 4 5 6]


In [15]:
array_c = np.arange(1, 10)
split_array = np.split(array_c, 3)
print(array_c)
print(split_array)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
