In [2]:
import numpy as np

array = np.array([10, 20, 30, 40, 50])
print(array[0])
print(array[-1])

10
50


In [3]:
print(array[1:4])

[20 30 40]


In [7]:
print(array[1:7])

[20 30 40 50]


In [8]:
print(array[-1:-7])

[]


In [10]:
bool_index = array > 25
print(bool_index)
print(type(bool_index))

[False False  True  True  True]
<class 'numpy.ndarray'>


In [11]:
index = [2, 3, 4]
print(array[index])

[30 40 50]


In [15]:
array = np.random.randint(1, 10, size=(3, 3))
print(array)
print(array[0, 1])

[[8 8 4]
 [8 2 2]
 [5 8 9]]
8


In [16]:
print(array[:2, :2])

[[8 8]
 [8 2]]
