Analisis de Ventas Mensuales con NumPy

El objetivo de este ejercicio es trabajar con arrays de NumPy para analizar y manipular datos de ventas de tres productos a lo largo de un año. A traves de diversas operaciones, exploraras como usar NumPy para obtener estadisticas, realizar manipulaciones avanzadas y aplicar tecnicas de indexacion para extraer informacion clave.

Paso 1: Crea arrays con datos de ventas
- Usa la libreria numpy para crear los siguientes arrays:
-- Meses: Un array con los nombres de los meses del año.
-- Ventas_A, Ventas_B, Ventas_C: Arrays que representan las ventas mensuales de tres productos diferentes.

In [55]:
import numpy as np

months = np.array(["Enero", "Febrero",
                   "Marzo", "Abril",
                   "Mayo", "Junio",
                   "Julio", "Agosto",
                   "Septiembre", "Octubre",
                   "Noviembre", "Diciembre"])
ventas_a = np.random.randint(150, 1000, size=(1, 12))
ventas_b = np.random.randint(120, 1000, size=(1, 12))
ventas_c = np.random.randint(100, 1000, size=(1, 12))
print(months)
print(ventas_a)
print(ventas_b)
print(ventas_c)

['Enero' 'Febrero' 'Marzo' 'Abril' 'Mayo' 'Junio' 'Julio' 'Agosto'
 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']
[[885 271 657 939 360 449 252 494 399 988 536 297]]
[[919 352 310 414 761 642 124 866 156 588 301 789]]
[[158 610 573 579 809 501 691 695 863 502 667 852]]


Paso 2: Estadisticas Basicas
- Calcula la media y la suma de ventas para los productos A, B y C usando las funciones de NumPy.
- Imprime estos valores en el formato siguiente:
-- Media de ventas Producto A:
-- Suma de ventas Producto A:
- Repite para los productos B y C.

In [2]:
mean_a = np.mean(ventas_a)
sum_a = np.sum(ventas_a)
print(f"Media de ventas Producto A: {mean_a:.2f}")
print(f"Suma de ventas Producto A: {sum_a}")
mean_b = np.mean(ventas_b)
sum_b = np.sum(ventas_b)
print(f"Media de ventas Producto B: {mean_b:.2f}")
print(f"Suma de ventas Producto B: {sum_b}")
mean_c = np.mean(ventas_c)
sum_c = np.sum(ventas_c)
print(f"Media de ventas Producto C: {mean_c:.2f}")
print(f"Suma de ventas Producto C: {sum_c}")

Media de ventas Producto A: 512.75
Suma de ventas Producto A: 6153
Media de ventas Producto B: 596.75
Suma de ventas Producto B: 7161
Media de ventas Producto C: 578.83
Suma de ventas Producto C: 6946


Paso 3: Manipulacion y Analisis de Datos
- Total de ventas por mes: Suma las ventas de los tres productos por cada mes.
- Promedio de ventas por producto: Calcula el promedio de ventas por producto.
- Mes con mayor y menor ventas: Identifica que mes tuvo el total de ventas mas alto y cual el mas bajo usando las funciones np.argmax y np.argmin.

In [56]:
ventas_por_mes = ventas_a + ventas_b + ventas_c
print("Ventas totales por mes (Enero a Diciembre): ")
print(ventas_por_mes)
promedio_de_ventas_a = np.mean(ventas_a)
promedio_de_ventas_b = np.mean(ventas_b)
promedio_de_ventas_c = np.mean(ventas_c)
print("Promedio de Ventas por Producto: ")
print(f"Ventas producto A: {promedio_de_ventas_a:.2f}")
print(f"Ventas producto B: {promedio_de_ventas_b:.2f}")
print(f"Ventas producto C: {promedio_de_ventas_c:.2f}")
mes_con_mayor_ventas = np.argmax(ventas_por_mes)
mes_con_menor_ventas = np.argmin(ventas_por_mes)
print(f"Mes con mayor ventas: {months[mes_con_mayor_ventas]}")
print(f"Mes con menor ventas: {months[mes_con_menor_ventas]}")

Ventas totales por mes (Enero a Diciembre): 
[[1962 1233 1540 1932 1930 1592 1067 2055 1418 2078 1504 1938]]
Promedio de Ventas por Producto: 
Ventas producto A: 543.92
Ventas producto B: 518.50
Ventas producto C: 625.00
Mes con mayor ventas: Octubre
Mes con menor ventas: Julio


Paso 4: Operaciones Avanzadas con NumPy
Reshape y Transposicion:
- Crea una matriz 2D con las ventas de los tres productos y transforma su forma (reshape) a un array tridimensional con dimensiones (3, 4, 3).
- Transpone la matriz de ventas para que las filas se conviertan en columnas.
- Invertir arrays: Invierte las ventas de cada producto en orden de meses.
- Aplanar la matriz: Convierte la matriz de ventas a un array unidimensional.

In [ ]:
matrix_ventas = np.vstack([ventas_a, ventas_b, ventas_c])
print(matrix_ventas)
matrix_reshaped = matrix_ventas.reshape(3, 4, 3)
print("Matriz de ventas reshaped: ")
print(matrix_reshaped)

matrix_t = matrix_ventas.T
print("Matriz transpuesta: ")
print(matrix_t)

matrix_reversed = matrix_ventas[:, ::-1]
print("Matriz invertida: ")
print(matrix_reversed)

matrix_flattened = matrix_ventas.flatten()
print("Matriz aplanada: ")
print(matrix_flattened)


Paso 5: Analisis de Elementos Unicos
- Utiliza np.unique para encontrar los elementos unicos en los datos de ventas y cuenta cuantas veces aparece cada uno.

In [22]:
unique_elements, conteo = np.unique(matrix_ventas, return_counts=True)
print("Elementos unicos: ")
print(unique_elements)
print("Conteo: ")
print(conteo)

Elementos unicos: 
[191 197 209 215 284 286 389 423 434 441 444 445 483 493 508 511 515 541
 543 553 558 579 654 661 700 772 844 846 848 863 865 891 895 921 941 989]
Conteo: 
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


Paso 6: Indexacion y Slicing
- Ventas del primer trimestre: Extrae las ventas de los tres primeros meses del año.
- Indexacion booleana: Selecciona los meses donde el total de ventas de los tres productos supere los 800.
- Seleccion avanzada: Usa una lista de indices para seleccionar las ventas de los meses pares (o selecciona los meses a tu eleccion) y muestra esas ventas en una nueva matriz.

In [57]:
print("Ventas del primer trimestre")
ventas_primer_trimestre = ventas_por_mes[0, :3]
print(ventas_primer_trimestre)

boolindex_array = ventas_por_mes[0] > 800
print("Meses donde sus ventas superaron $800: ")
print(months[boolindex_array])

pairs_index = [1, 3, 5, 7, 9, 11]
slicing_months_by_pairs = months[pairs_index]
print("Ventas meses pares del año: ")
print(slicing_months_by_pairs)
print(ventas_por_mes[0][pairs_index])

Ventas del primer trimestre
[1962 1233 1540]
Meses donde sus ventas superaron $800: 
['Enero' 'Febrero' 'Marzo' 'Abril' 'Mayo' 'Junio' 'Julio' 'Agosto'
 'Septiembre' 'Octubre' 'Noviembre' 'Diciembre']
Ventas meses pares del año: 
['Febrero' 'Abril' 'Junio' 'Agosto' 'Octubre' 'Diciembre']
[1233 1932 1592 2055 2078 1938]
