Acceder a elementos especificos:
- Crea un arreglo de 10 numeros y accede al cuarto
y penultimo elemento usando positivos y negativos.

In [4]:
import numpy as np
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(array[3])
print(array[-2])

4
9


Slicing de arreglos:
- Dado un arreglo de numeros del 1 al 20, extrae los elementos entre las posiciones 3 y 7, luego los elementos de las ultimas 5 posiciones.

In [11]:
array = np.arange(1, 21)
print(array)
print(array[2:7])
print(array[-5:])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[3 4 5 6 7]
[16 17 18 19 20]


Indexing con booleanos:
- Crea un arreglo de numeros aleatorios entre 0 y 100. Usa una expresion booleana para acceder solo a los numeros mayores a 50.

In [22]:
array = np.random.randint(0, 101, size=10)
print(array)
boolean_index = array > 50
print(array[boolean_index])

[94 78 71 64 23 27 62 54 14 26]
[94 78 71 64 62 54]


Indexacion con multiples indices:
- Dado un arreglo de 8 elementos, crea una lista de indices para acceder a los elementos en las posiciones 1, 4 y 6.

In [24]:
array = np.arange(1, 9)
print(array)
index_list = [1, 4, 6]
print(array[index_list])

[1 2 3 4 5 6 7 8]
[2 5 7]


Matrices bidimensionales:
- Genera una matriz 4x4 de numeros aleatorios entre 10 y 50, accede a la submatriz de 2x2 ubicada en la esquina inferior derecha.

In [36]:
matrix = np.random.randint(10, 51, size=(4, 4))
print(matrix)
print(matrix[2:, 2:])

[[36 18 32 20]
 [35 18 35 46]
 [35 21 11 16]
 [36 11 24 36]]
[[11 16]
 [24 36]]
