In [2]:
import numpy as np
escalar = np.array(42)
print(type(escalar))
print(escalar)

<class 'numpy.ndarray'>
42


In [3]:
vector = np.array([30, 29, 35, 31, 33, 36, 42])
print(vector)

[30 29 35 31 33 36 42]


In [4]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matrix)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
tensor = np.array([[[1, 2], [3, 4], [5, 6], [7, 8]]])
print(tensor)

[[[1 2]
  [3 4]
  [5 6]
  [7 8]]]


In [6]:
array_arange = np.arange(10)
print(array_arange)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
eye_matrix = np.eye(3)
print(eye_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [8]:
diag = np.diag([1, 2, 3])
print(diag)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [9]:
random = np.random.random((2, 3))
print(random)

[[0.69559321 0.23524434 0.35127006]
 [0.07331281 0.24611677 0.26194569]]
